import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.proc.BadJOSEException;
import net.minidev.json.JSONObject;
import org.junit.jupiter.api.Test;

import java.net.MalformedURLException;
import java.text.ParseException;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AccessTokenValidationTest {

    AccessTokenValidation cut = new AccessTokenValidation();

    @Test
    void validate() throws MalformedURLException, ParseException, BadJOSEException, JOSEException {
        String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJUNnZaa1J3WERQRXU1X0YzRldBSjAwN2ZqWWNCR043VjVkV1NBTTctN1IwIn0.eyJleHAiOjE2MTgzMzMxNjAsImlhdCI6MTYxODMzMjg2MCwianRpIjoiM2Y4MTJmM2MtODNkNy00YzkwLTliZjUtNWVlODZiOGU5MTlhIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLXFzLmRjLmdscy1ncm91cC5ldS9hdXRoL3JlYWxtcy9nbHMiLCJhdWQiOlsiY3VzdG9tZXItcG9ydGFsLXNwYSIsImFjY291bnQiXSwic3ViIjoiY2ZlOTUzMzMtYzNiMC00MDAzLWE5MTQtNmJkODUxZjQ1MjIwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY3VzdG9tZXItcG9ydGFsLXFhIiwic2Vzc2lvbl9zdGF0ZSI6IjllZDFlNTM3LTUwMzMtNGU1MS1iNGY2LTg3ZGNlMWM3ZjZlYSIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImN1c3RvbWVyLXBvcnRhbC1zcGEiOnsicm9sZXMiOlsiY3VwLnJlYWQiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHJvbGVzIHByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJvbGFuZC53ZWJlci50ZXN0IiwidXNlcl9ubyI6IjI1ODQzMTIifQ.c_Z5skS04Twgwa5ddiwnYURRLrTjQDGXDui0-0LRDfHb4P8akbJ9yjToDM9fthxPY3VkmUeADr5-Rr18HYMvglKflExPdXAQdWJan_fTdpfCE_ra18SHYITdMCe9mS_Q81F9svoaZRW0W1uuYfhH31Fnju14b56TLjnRWy3gRFRF7surDJuZYlSgL7SgKx2kVh6_4XhszgytCo0gYDEJD8dCz15Ab4SC_ZsWbFTZsAeuAbdbcgqrkcJd76XDi2qsG5Z0SO7-c9p9fVl5GklPFKdxLxoBaZsA2tc2M112lsLVPA6rSfBOBs7y3OPHSCPrMGCIIz7KDtkaUlPgZxWZ-g";

        JSONObject json =  cut.validate(token);
        assertTrue(json.containsKey("sub"));

    }
}